// flow-typed signature: 7db6cbaecd7a125deacd539624791f48
// flow-typed version: <<STUB>>/node-style-loader_v^0.0.1-alpha/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-style-loader/clientCleanup' {
  declare module.exports: any;
}

declare module 'node-style-loader/collect' {
  declare module.exports: any;
}

declare module 'node-style-loader/lib/styleStack' {
  declare module.exports: any;
}

declare module 'node-style-loader/loader' {
  declare module.exports: any;
}

declare module 'node-style-loader/test/collect.test' {
  declare module.exports: any;
}

declare module 'node-style-loader/test/setup' {
  declare module.exports: any;
}

declare module 'node-style-loader/test/styleStack.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-style-loader/clientCleanup.js' {
  declare module.exports: $Exports<'node-style-loader/clientCleanup'>;
}
declare module 'node-style-loader/collect.js' {
  declare module.exports: $Exports<'node-style-loader/collect'>;
}
declare module 'node-style-loader/lib/styleStack.js' {
  declare module.exports: $Exports<'node-style-loader/lib/styleStack'>;
}
declare module 'node-style-loader/loader.js' {
  declare module.exports: $Exports<'node-style-loader/loader'>;
}
declare module 'node-style-loader/test/collect.test.js' {
  declare module.exports: $Exports<'node-style-loader/test/collect.test'>;
}
declare module 'node-style-loader/test/setup.js' {
  declare module.exports: $Exports<'node-style-loader/test/setup'>;
}
declare module 'node-style-loader/test/styleStack.test.js' {
  declare module.exports: $Exports<'node-style-loader/test/styleStack.test'>;
}
