// flow-typed signature: bc4e2f5a22f2f50bdddbdab4de320aef
// flow-typed version: <<STUB>>/prop-types_v^15.5.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-types' {
  declare module.exports: any;
}
