// flow-typed signature: 5e398a81fd1f085cfec2e11a0b3c0e7c
// flow-typed version: <<STUB>>/redux-saga-testing_v^1.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-testing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-testing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-testing/ava/01.simple.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/ava/02.simple-saga.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/ava/03.saga-with-data.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/ava/04.saga-with-exception.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/ava/05.saga-with-input.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/ava/10.all-in-one-example.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/01.simple.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/02.simple-saga.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/03.saga-with-data.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/04.saga-with-exception.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/05.saga-with-input.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/jest/10.all-in-one-example.spec' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/main' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/01.simple.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/02.simple-saga.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/03.saga-with-data.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/04.saga-with-exception.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/05.saga-with-input.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/mocha/10.all-in-one-example.test' {
  declare module.exports: any;
}

declare module 'redux-saga-testing/src/helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-testing/ava/01.simple.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/01.simple.test'>;
}
declare module 'redux-saga-testing/ava/02.simple-saga.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/02.simple-saga.test'>;
}
declare module 'redux-saga-testing/ava/03.saga-with-data.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/03.saga-with-data.test'>;
}
declare module 'redux-saga-testing/ava/04.saga-with-exception.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/04.saga-with-exception.test'>;
}
declare module 'redux-saga-testing/ava/05.saga-with-input.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/05.saga-with-input.test'>;
}
declare module 'redux-saga-testing/ava/10.all-in-one-example.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/ava/10.all-in-one-example.test'>;
}
declare module 'redux-saga-testing/jest/01.simple.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/01.simple.spec'>;
}
declare module 'redux-saga-testing/jest/02.simple-saga.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/02.simple-saga.spec'>;
}
declare module 'redux-saga-testing/jest/03.saga-with-data.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/03.saga-with-data.spec'>;
}
declare module 'redux-saga-testing/jest/04.saga-with-exception.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/04.saga-with-exception.spec'>;
}
declare module 'redux-saga-testing/jest/05.saga-with-input.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/05.saga-with-input.spec'>;
}
declare module 'redux-saga-testing/jest/10.all-in-one-example.spec.js' {
  declare module.exports: $Exports<'redux-saga-testing/jest/10.all-in-one-example.spec'>;
}
declare module 'redux-saga-testing/main.js' {
  declare module.exports: $Exports<'redux-saga-testing/main'>;
}
declare module 'redux-saga-testing/mocha/01.simple.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/01.simple.test'>;
}
declare module 'redux-saga-testing/mocha/02.simple-saga.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/02.simple-saga.test'>;
}
declare module 'redux-saga-testing/mocha/03.saga-with-data.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/03.saga-with-data.test'>;
}
declare module 'redux-saga-testing/mocha/04.saga-with-exception.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/04.saga-with-exception.test'>;
}
declare module 'redux-saga-testing/mocha/05.saga-with-input.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/05.saga-with-input.test'>;
}
declare module 'redux-saga-testing/mocha/10.all-in-one-example.test.js' {
  declare module.exports: $Exports<'redux-saga-testing/mocha/10.all-in-one-example.test'>;
}
declare module 'redux-saga-testing/src/helper.js' {
  declare module.exports: $Exports<'redux-saga-testing/src/helper'>;
}
